global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "outcurr-app"
    metrics_path: "/outcurrapi/actuator/prometheus" # Aquí se mueve fuera de static_configs
    static_configs:
<<<<<<< HEAD
      - targets: ['outcurr-app:9092']
=======
      - targets: ["outcurr-app:9092"]
>>>>>>> 75b9665e434240ceab0a9180889f5cbbd840ef6d

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
