server:
  http_listen_port: 9080
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "outcurr-app-logs"
    static_configs:
      - targets: ['outcurr-app:9092']
        labels:
          job: "outcurr-app"
          __path__: /var/log/outcome-curr-mgmt/*.log
    pipeline_stages: